### ISSUE TITLE
dependency police: brfs still required as dep?

### ISSUE THREAD

**Issue by thisconnect** [dignifiedquire/protons#2]
Is it still required to have brfs as dependency?
protons as far as I can see never uses fs.readFile 
which would be browserified with https://www.npmjs.com/package/brfs

**Comment by thisconnect** [comment]
related

https://snyk.io/test/npm/ipfs-api/14.3.5
https://github.com/ipfs/js-ipfs-api/issues/610

**Comment by dignifiedquire** [comment]
I believe it should be safe to pull it out, I simply forgot about it when creating the fork.

**Comment by thisconnect** [comment]
I am not 100% :)
Should I try running this PR on some of the dependents of protons that have browser tests against thisconnect/protons#dep/remove/brfs ?

https://www.npmjs.com/browse/depended/protons

**Comment by dignifiedquire** [comment]
that would be great if you can do that!
